data :
  train_annot_path  : 'data/updated_train_annotation.json'
  val_annot_path    : 'data/updated_train_annotation.json'
  task : 'field_instance_segmentation'
  model_config_file : "COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"   # path to config file is present in detectron2's model zoo
  OUTPUT_DIR : 'results/detectron_2'  # path to save the model
  train_dir : 'data/3channel_images'
  val_dir : 'data/3channel_images'
  evaluator_type : 'coco'  # type of evaluator to be used
  categories :    # ordering is important, visit "register_lightdata" function
    - field
  thing_colors:
    - [0, 100, 0]


# Solver configuration
MAX_ITER : 500
BASE_LR  : 0.00025
IMS_PER_BATCH : 2  # "batch size" commonly known to deep learning people
STEPS :   # steps at which learning rate is reduced
  - 150
  - 300
  - 450
NUM_WORKERS : 4
BATCH_SIZE_PER_IMAGE  : 400  # ROI_HEADS.BATCH_SIZE_PER_IMAGE
NUM_CLASSES           : 1    # number of classes in the dataset


