dir : 'results'
MAX_EPOCHS : 30
BATCH_SIZE : 16
lr : !!float 1e-4
weight_decay : !!float 1e-6
NUM_WORKERS : 4
img_dir : 'data/3channel_images'
mask_dir : 'data/masks'
ckpt_file_name : 'Epoch-{epoch}__Loss-{val_loss:.2f}'

# CALLBACK related config
callbacks:
  ModelCheckpoint:
    monitor: 'val_loss'
    mode: 'min'
    save_top_k: 2
    save_last: True
  EarlyStopping:
    monitor: 'val_loss'
    mode: 'min'
    min_delta : 0.0001
    patience : 8