dir : 'results'
MAX_EPOCHS : 20
BATCH_SIZE : 64
lr : !!float 1e-3
weight_decay : !!float 1e-5
log_every_n_steps : 8   # should be less than the number of steps in an epoch, i.e. BATCH_SIZE
NUM_WORKERS : 95
img_dir : 'data/patched_images'
mask_dir : 'data/patched_masks'
train_df : 'data/train_patch_df.csv'
ckpt_file_name : 'Epoch-{epoch}__Loss-{val_loss:.2f}'
plot_masks : 5

# CALLBACK related config
callbacks:
  ModelCheckpoint:
    monitor: 'train_loss'
    mode: 'min'
    save_top_k: 2
    save_last: True
  EarlyStopping:
    monitor: 'val_loss'
    mode: 'min'
    min_delta : 0.0001
    patience : 8