DeepLabV3_config:
  activation: sigmoid
  classes: 1
  decoder_channels: 256
  encoder_depth: 5
  encoder_name: resnet50
  encoder_weights: imagenet
  in_channels: 12
  upsampling: 8
FPN_config:
  activation: sigmoid
  classes: 1
  decoder_dropout: 0.2
  decoder_merge_policy: add
  decoder_pyramid_channels: 256
  decoder_segmentation_channels: 128
  encoder_depth: 5
  encoder_name: resnet50
  encoder_weights: imagenet
  in_channels: 3
  upsampling: 4
UnetPlusPlus_config:
  activation: sigmoid
  classes: 1
  decoder_attention_type: scse
  decoder_use_batchnorm: true
  encoder_depth: 5
  encoder_name: resnet50
  encoder_weights: imagenet
  in_channels: 3
Unet_config:
  activation: sigmoid
  classes: 1
  decoder_attention_type: scse
  encoder_name: resnet50
  encoder_weights: imagenet
  in_channels: 3
model_name: DeepLabV3
